version: '3.8'
services:
  dev-db:
    image: postgres:13
    restart: always
    ports:
      - 33000:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    volumes:
      - my-db:/var/lib/pos
volumes:
  my-db:
